# Generated by Django 6.1.1 on 2026-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('email_domain', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('original_source', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source_channel', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('source_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
